apps/main/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
]

urlpatterns = [
    path('article/', views.blog_view, name='blog'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
]

apps/main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='posts', null=True, default=None)
    
    title = models.CharField(verbose_name='Заголовок', max_length=255)
    content = models.TextField(verbose_name='Контент')
    image = models.ImageField(verbose_name='Малюнок', upload_to='post_images/')
    is_published = models.BooleanField(verbose_name='Опубліковано', default=False, blank=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    views = models.IntegerField(verbose_name='Перегляди', default=0, blank=True)
    created_at = models.DateTimeField(verbose_name='Дата створення', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата оновлення', auto_now=True)
    
    def __str__(self):
        return f'{self.title} - {self.created_at} - {self.is_published}'
    
    class Meta: # Це потрібно для відображення моделі в адмінці
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости'
        ordering = ['-created_at']
        
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост', related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='comments', null=True, default=None)
    content = models.TextField(verbose_name='Контент')
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)
    created_at = models.DateTimeField(verbose_name='Дата створення', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата оновлення', auto_now=True)
    
    def __str__(self):
        return f'{self.author} - {self.created_at}'
    
    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        ordering = ['created_at']
        # models.py
        
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

class Dislike(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='dislikes')

apps/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms
from .forms import PostForm, CommentForm
from django.shortcuts import render
from .models import Post

# Create your views here.
# @login_required
def index(request):
    
    posts = Post.objects.filter(is_published=True)
    create_form = PostForm()
    
    context = {
        'posts': posts,
        'form': create_form
    }
    
    return render(request, 'blog/index.html', context)

@login_required
def post(request, post_id):
    # post = Post.objects.get(id=post_id)
    form_comment = CommentForm()
    post = get_object_or_404(Post, id=post_id)
    post.views += 1
    post.save()
    context = {
        'post': post,
        'comment_form': form_comment,
    }
    
    return render(request, 'blog/post.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Пост створено')
    return redirect('blog:index')

@login_required
def comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            print(comment)
            comment.post = post
            comment.author = request.user
            comment.save()
            messages.success(request, 'Коментар додано')
    return redirect('blog:post', post_id=post_id)

@login_required
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    post.save()
    return JsonResponse({'likes': post.likes.count()})

@login_required
def like_comment(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, post__id=post_id)
    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)
    comment.save()
    return JsonResponse({'likes': comment.likes.count()})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    post.delete()
    messages.success(request, 'Пост видалено')
    return redirect('members:profile')

def blog_page(request):
    posts = Post.objects.all()
    return render(request, 'blog/blog_page.html', {'posts': posts})


def profile(request):
    user_posts = Post.objects.filter(author=request.user)
    num_posts = user_posts.count()
    return render(request, 'profile.html', {'num_posts': num_posts})

apps/main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dom Piva</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl7/1L_dstPt3HV5HzF6Gvk/e3s4Wz6iJgD/+ub2oU" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">My Website</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="about.html">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contacts.html">Contacts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="custom.html">Custom</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-5">
        
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybB5IXNxFwWQfE7u8Lj+XJHAxKlXiG/8rsrtpb6PEdzD828Ii" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
</body>
</html>

apps/main/templates/main/login.html
<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <h3 class="text-center">Логін</h3>
        <form method="post">
            <div class="mb-3">
                <label for="username" class="form-label">Ім'я користувача</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Пароль</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Увійти</button>
        </form>
</div>

apps/main/templates/main/post.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}



{% block content %}
    

        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <img src="{{post.image.url}}" class="img-fluid rounded-3" width="100%" alt="...">
            <h3>{{post.title}}</h3>
            {% if user.is_authenticated and user == post.author %}
                <a href="{% url 'blog:edit_post' post.id %}" class="btn btn-sm btn-outline-primary">Редагувати</a>
                <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-sm btn-outline-danger">Видалити</a>
            {% endif %}
            <small class="text-muted">{{post.created_at}}</small>
            <small class="text-muted">{{post.author}}</small>
            <small class="text-muted">{{post.category}}</small>
            <div class="d-flex justify-content-between text-center">
                <h5><span class="badge ">👁️ {{post.views}}</span></h5>
                <h5><span class="badge ">🗨️ {{post.comments.count}}</span></h5>
                <h5><span class="btn btn-secondary" id="btn_like">👍 {{post.likes.count}}</span></h5>
                <h5><span class="btn btn-secondary" id="btn_dislike"> 👎 {{post.dislikes.count}}</span></h5>
            </div>
            <hr class="my-4">
            <p>{{post.content|safe}}</p>
        </div>
        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <h5>Коментарі</h5>
            🗨️ {{post.comments.count}}
            <hr class="mx-2">
            <form action="{% url 'blog:comment' post.id %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="comment" class="form-label">Ваш коментар</label>
                    <textarea class="form-control" id="comment" name="content" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Відправити</button>
            </form>
            <hr class="my-4">
            {%for comment in post.comments.all%}
                <div class="d-flex justify-content-between">
                    
                    <div>
                        <button type="button" class="btn btn-secondary" onclick="like_comment({{comment.id}})" id="btn_like_comment_{{comment.id}}">❤️ {{comment.likes.count}}</button>

                        <h5>{{comment.author}}</h5>
                        <p>{{comment.content}}</p>
                    </div>
                    <div>
                        <small class="text-muted text-end">{{comment.created_at}}</small>
                    </div>
                </div>
                <hr>
            {%endfor%}
        </div>


<script>
    document.getElementById('btn_like').addEventListener('click', function(){
        fetch('{% url "blog:like" post.id %}')
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like').innerText = `👍 ${data.likes}`;
            document.getElementById('btn_like').innerText = `👎 ${data.dislikes}`;
        })
        .catch(error => console.log(error));
    });

    function like_comment(comment_id){
        fetch('{% url "blog:like_comment" post.id 0 %}'.replace('0', comment_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like_comment_' + comment_id).innerText = `❤️ ${data.likes}`;
        })
        .catch(error => console.log(error));
    }

</script>
{% endblock %}